#ifndef SSCB_CAN_FRAME_H
#define SSCB_CAN_FRAME_H

#include "common/sscb_types.h"

typedef struct {
    uint16_t id;
    uint8_t dlc;
    uint8_t data[8];
} sscb_can_frame_t;

#define SSCB_CAN_ID_REALTIME_BASE 0x100u
#define SSCB_CAN_ID_FAULT_BASE 0x200u
#define SSCB_CAN_ID_HEARTBEAT_BASE 0x300u
#define SSCB_CAN_ID_PARAM_BASE 0x400u
#define SSCB_CAN_ID_TIME_SYNC_BASE 0x500u
#define SSCB_CAN_ID_CONTROL_BASE 0x600u
#define SSCB_CAN_ID_FAULT_RECORD_BASE 0x700u

#define SSCB_CAN_FIXED_NODE_ID 1u
#define SSCB_CAN_ID_REALTIME_FIXED (SSCB_CAN_ID_REALTIME_BASE + SSCB_CAN_FIXED_NODE_ID)
#define SSCB_CAN_ID_FAULT_FIXED (SSCB_CAN_ID_FAULT_BASE + SSCB_CAN_FIXED_NODE_ID)
#define SSCB_CAN_ID_HEARTBEAT_FIXED (SSCB_CAN_ID_HEARTBEAT_BASE + SSCB_CAN_FIXED_NODE_ID)
#define SSCB_CAN_ID_PARAM_FIXED (SSCB_CAN_ID_PARAM_BASE + SSCB_CAN_FIXED_NODE_ID)
#define SSCB_CAN_ID_TIME_SYNC_FIXED (SSCB_CAN_ID_TIME_SYNC_BASE + SSCB_CAN_FIXED_NODE_ID)
#define SSCB_CAN_ID_CONTROL_FIXED (SSCB_CAN_ID_CONTROL_BASE + SSCB_CAN_FIXED_NODE_ID)

#endif
