#ifndef SSCB_BOARD_RESOURCES_H
#define SSCB_BOARD_RESOURCES_H

#define SSCB_ADC_SAMPLE_PERIOD_US 20u
#define SSCB_RMS_PERIOD_MS 1u

#define SSCB_CPU_HZ 100000000ul
#define SSCB_LSPCLK_HZ 25000000ul
#define SSCB_EPWM3_BASE_CLOCK_HZ SSCB_CPU_HZ
#define SSCB_EPWM3_PERIOD_TICKS ((SSCB_EPWM3_BASE_CLOCK_HZ / 1000000ul) * SSCB_ADC_SAMPLE_PERIOD_US)
#define SSCB_EPWM3_DC_BLANKING_TICKS 30u

#define SSCB_ADC_VOLTAGE_CHANNEL_ADCC4 4u
#define SSCB_ADC_CURRENT_PGA_CHANNEL_A2 2u
#define SSCB_ADC_CURRENT_RAW_CHANNEL_B3 3u
#define SSCB_ADC_TEMP_CHANNEL_B1 1u

#define SSCB_GPIO_EPWM3A 4u
#define SSCB_GPIO_FLT_N 3u
#define SSCB_GPIO_RDYC 2u
#define SSCB_GPIO_I2C_SCL 1u
#define SSCB_GPIO_I2C_SDA 0u
#define SSCB_GPIO_CANB_TX 16u
#define SSCB_GPIO_CANB_RX 17u
#define SSCB_GPIO_SPIB_SOMI 6u
#define SSCB_GPIO_SPIB_SIMO 7u
#define SSCB_GPIO_SPIB_CLK 14u
#define SSCB_GPIO_SPIB_STE 15u

#define SSCB_CAN_NODE_ID_DEFAULT SSCB_CAN_FIXED_NODE_ID
#define SSCB_CAN_BITRATE 500000u
#define SSCB_CAN_TX_OBJECT 1u
#define SSCB_CAN_RX_PARAM_OBJECT 2u
#define SSCB_CAN_RX_TIME_OBJECT 3u
#define SSCB_CAN_RX_CONTROL_OBJECT 4u
#define SSCB_CAN_RX_FAULT_RECORD_OBJECT 5u

#define SSCB_SPIB_BITRATE 1000000u

#define SSCB_I2CA_BITRATE 400000u
#define SSCB_GATE_DRIVER_I2C_ADDR_7BIT 0x0Du
#define SSCB_GATE_DRIVER_I2C_ADDR_8BIT 0x1Au

#define SSCB_FRAM_SIZE_BYTES 0x40000ul
#define SSCB_FRAM_BOOT_INFO_ADDR 0x00000ul
#define SSCB_FRAM_PARAM_A_ADDR 0x00100ul
#define SSCB_FRAM_PARAM_B_ADDR 0x00500ul
#define SSCB_FRAM_CALIBRATION_ADDR 0x00900ul
#define SSCB_FRAM_FAULT_INDEX_ADDR 0x01000ul
#define SSCB_FRAM_FAULT_RECORDS_ADDR 0x01100ul

#define SSCB_FRAM_CMD_WREN 0x06u
#define SSCB_FRAM_CMD_WRITE 0x02u
#define SSCB_FRAM_CMD_READ 0x03u

#endif
